name: topictap
version: '1.0.0'
category: Services
author: Arbor Networks
maintainer: mayhem@arbor.net
copyright: Arbor Networks
license: MIT
homepage: https://github.com/packetloop/topictap#readme
extra-source-files:
- README.md
- tests/resources/simple.avsc
default-extensions:
- BangPatterns
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
dependencies:
- base >=4.7 && <5
- aeson
- amazonka
- amazonka-core
- amazonka-s3
- avro
- base16-bytestring
- bifunctors
- bytestring
- conduit
- conduit-extra
- containers
- cryptohash
- datadog
- directory
- exceptions
- fast-logger
- hs-arbor-logger
- http-client
- http-types
- hw-conduit
- hw-kafka-avro
- hw-kafka-client
- hw-kafka-conduit
- lens
- monad-control
- monad-logger
- mtl
- network
- random
- resourcet
- text
- transformers
- transformers-base
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  exposed-modules:
  - App
  - App.AppEnv
  - App.AppError
  - App.Application
  - App.AppState
  - App.AWS.Env
  - App.AWS.S3
  - App.Codec
  - App.Kafka
  - App.Options
  - App.ToSha256Text
  dependencies:
  - base64-bytestring
  - conduit-combinators
  - http-types
  - optparse-applicative
  - split
  when:
  - condition: os(osx)
    cpp-options:
    - -D__attribute__(A)=
    - -D_Nullable=
    - -D_Nonnull=
executables:
  topictap:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - topictap
    - conduit-combinators
    - optparse-applicative
    when:
    - condition: os(osx)
      cpp-options:
      - -D__attribute__(A)=
      - -D_Nullable=
      - -D_Nonnull=
tests:
  tests:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -Wall
    - -threaded
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - base64-bytestring
    - hedgehog
    - hspec
    - hw-hedgehog
    - hw-hspec-hedgehog
    - lens-aeson
    - topictap
    when:
    - condition: os(osx)
      cpp-options:
      - -D__attribute__(A)=
      - -D_Nullable=
      - -D_Nonnull=
