resolver: lts-10.10

packages:
- '.'
- location:
    git: git@github.com:packetloop/arbor-datadog.git
    commit: 317f6d2a8b29fc807c98e69d9fabc428b635e5f1
  extra-dep: true
- location:
    git: git@github.com:packetloop/hs-arbor-logger.git
    commit: 85f56acbd43625793b09aa5281c6224a7cca7d76
  extra-dep: true
- location:
    git: git@github.com:arbor/antiope.git
    commit: aaae69408f4852e41089f8e14080a2c4f6acc81f
    subdirs:
      - antiope-core
      - antiope-s3
      - antiope-dynamodb
  extra-dep: true

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- async-pool-0.9.0.2
- avro-0.3.0.1
- hedgehog-0.5.3
- hw-conduit-0.2.0.3
- hw-hspec-hedgehog-0.1.0.4
- hw-kafka-avro-1.4.0
- hw-kafka-client-2.5.0
- hw-kafka-conduit-2.5.0
- pure-zlib-0.6.2

# Override default flag values for local packages and extra-deps
flags: {}

extra-package-dbs: []
