resolver: lts-10.10

packages:
- '.'
- location:
    git: git@github.com:packetloop/datadog.git
    commit: d7c5b246e02677596ca03bf699c490d0c4470066
  extra-dep: true
- location:
    git: git@github.com:packetloop/hs-arbor-logger.git
    commit: 85f56acbd43625793b09aa5281c6224a7cca7d76
  extra-dep: true

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- async-pool-0.9.0.2
- avro-0.2.1.1
- hedgehog-0.5.3
- hw-conduit-0.2.0.3
- hw-hspec-hedgehog-0.1.0.4
- hw-kafka-avro-1.4.0
- hw-kafka-client-2.4.1
- hw-kafka-conduit-2.4.0
- pure-zlib-0.6.2

# Override default flag values for local packages and extra-deps
flags: {}

extra-package-dbs: []
